server:
  port: 8081
spring:
  profiles:
    default: "dev"
    active: "dev"

  datasource:
    url: "jdbc:postgresql://localhost:5432/beatgear"
    username: "postgres"
    password: ""

    jpa:
      hibernate:
        ddl-auto: "update" # oder "none", "validate", "create-drop", je nach Bedarf
      properties:
        hibernate:
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
