version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_hardware_management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sql/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_hardware_management
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - /keycloak/import:/opt/keycloak/data/import
    command: start-dev
