"""Initial migration

Revision ID: 5a37180a2353
Revises: 
Create Date: 2024-11-20 18:26:14.586472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a37180a2353'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('CONTROLLER', 'LIGHT', 'CABLE_XLR', 'PLUG_COLD_APPLIANCE', 'LAPTOP_STAND', 'OTHER', name='hardwarecategory'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('price_per_day', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings_to_hardware',
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('hardware_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], )
    )
    op.drop_table('booking_to_bookings')
    op.add_column('bookings', sa.Column('parent_booking_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'bookings', ['parent_booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'parent_booking_id')
    op.create_table('booking_to_bookings',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('child_booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_to_bookings_booking_id_fkey'),
    sa.ForeignKeyConstraint(['child_booking_id'], ['bookings.id'], name='booking_to_bookings_child_booking_id_fkey')
    )
    op.drop_table('bookings_to_hardware')
    op.drop_table('hardware')
    # ### end Alembic commands ###
