"""Initial migration

Revision ID: 7866390e219f
Revises: 
Create Date: 2024-11-20 18:20:03.822817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7866390e219f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('CONTROLLER', 'LIGHT', 'CABLE_XLR', 'PLUG_COLD_APPLIANCE', 'LAPTOP_STAND', 'OTHER', name='hardwarecategory'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('price_per_day', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings_to_hardware',
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('hardware_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], )
    )
    op.alter_column('booking_to_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('booking_to_bookings', 'child_booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_to_bookings', 'child_booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('booking_to_bookings', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('bookings_to_hardware')
    op.drop_table('hardware')
    # ### end Alembic commands ###
