server:
  port: 8081
spring:
  profiles:
    default: "dev"
    active: "dev"

  datasource:
    url: "jdbc:postgresql://localhost:5432/beatgear"
    username: "postgres"
    password: ""

  flyway:
    enabled: true
    validate-on-migrate: true
    url: "jdbc:postgresql://localhost:5432/beatgear"
    user: postgres
    password: ""
